DEFAULT_MODEL="google_genai:gemini-3.6-flash"
TAVILY = 'tavily:tavily-3.6-13b'
LLAMA ="groq:meta-llama/llama-prompt-guard-2-22m"
DEFAULT_TEMPERATURE=0.5
CHUNK_SIZE=800
CHUNK_OVERLAP=100
MODEL_PATH = "models/best_pneumonia_model.keras"
IMAGE_SIZE = 28
THRESHOLD = 0.1